model_list:
  - model_name: gpt-4.1
    litellm_params:
      model: gpt-4.1
  - model_name: gpt-4o
    litellm_params:
      model: gpt-4o
  - model_name: gpt-4o-mini
    litellm_params:
      model: gpt-4o-mini
  - model_name: text-embedding-3-small
    litellm_params:
      model: text-embedding-3-small
  - model_name: text-embedding-3-large
    litellm_params:
      model: text-embedding-3-large

litellm_settings:
  set_verbose: True
  cache: True          # set cache responses to True, litellm defaults to using a redis cache