site_name: LMM-Vibes Documentation
site_description: Documentation for the LMM-Vibes project
site_author: LMM-Vibes Team

# Repository
repo_name: LMM-Vibes
repo_url: https://github.com/lisabdunlap/LMM-Vibes

# Theme
theme:
  name: material
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-auto
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - search.suggest
    - search.highlight
    - content.code.copy

# Navigation
nav:
  - Home: index.md
  - Getting Started:
    - Installation: getting-started/installation.md
    - Quick Start: getting-started/quick-start.md
  - User Guide:
    - Basic Usage: user-guide/basic-usage.md
    - Configuration: user-guide/configuration.md
  - API Reference:
    - Core Functions: api/core.md
    - Utilities: api/utilities.md
  - Development:
    - Contributing: development/contributing.md
    - Testing: development/testing.md

# Plugins
plugins:
  - search

# Extra CSS and JS
extra_css:
  - stylesheets/extra.css

# Copyright
copyright: Copyright &copy; 2024 LMM-Vibes Team
